### PR TITLE
add inclusive language

### PR DESCRIPTION
**Pull request by yifeiwu**

### CODE REVIEW

**Comment by grosser** [comment]
is this all a certain client app needs ?
... otherwise I think there are a bunch of other methods that need an alias
having methods to use things that are different from the config and services etc could lead to confusion, 
 also making it harder to find things when greping through the codebase

**Comment by yifeiwu** [comment]
Yes, mainly to appease the inclusive language check app. Not sure what's a good solution.

**Comment by grosser** [comment]
can also disable the app I think ... there is some comment or so

**Comment by bquorning** [comment]
👎 Then I’d prefer the approach taken in #216.

**Comment by grosser** [comment]
FYI config can be at .github/term-check.yaml ... see https://github.com/zendesk/term-check for all options

**Comment by yifeiwu** [comment]
thanks!

**Pull request closed without merging**
