### PR TITLE
Remove seemingly unused patch

### PR DESCRIPTION
**Pull request by bquorning**
Does anyone recognize this code, and know why/if it was needed?

### CODE REVIEW

**Comment by bquorning** [comment]
cc/ @grosser @osheroff

**Comment by osheroff** [comment]
how does it "seem unused"? debuggers show no exercise in the test suite?

**Comment by grosser** [comment]
git blame to the rescue ?

**Comment by bquorning** [comment]
I added a `puts` to lines 35 and 37 (each branch of the condition) and it seems that all specs go though the branch that does nothing.

**Comment by bquorning** [comment]
Hmm, *could* it be because `ActiveRecordShards::ConnectionSpecification` is not defined when this code is loaded?

**Comment by bquorning** [comment]
> git blame to the rescue ?

9cb3918d94e8eb3c2d6ca965873a8d57d2329b14

**Comment by bquorning** [comment]
@osheroff and @grosser, could you please re-review this one?

**Comment by grosser** [comment]
I have no idea ... remove and deploy to master and see if shard switching works ...

**Comment by osheroff** [comment]
So the thing here is that this is patching `ActiveRecord::Base.establish_connection`, which should really only ever be called externally.  I'm technically fine removing this if we find it's genuinely unused, but vetting that is tougher than just sprinkling a `puts` around the specs; all  that's proving is the code is untested.

**Pull request closed without merging**
