### PR TITLE
Replace master/slave terminology with primary/replica

### PR DESCRIPTION
**Pull request by pschambacher**

### CODE REVIEW

**Comment by craig-day** [comment]
Should we keep both terms in a first pass to make the transition easier?

**Comment by bquorning** [comment]
I’m fine with the proposed change, but 1) we need to ensure backwards compatibility (until next major version), and 2) master branch is currently a Rails 5.2 compatibility release candidate. I’d like to have that 5.2 compatibility properly released before merging this change.

**Comment by libo** [comment]
It would be nice with a description.

**Comment by brianburnszd** [comment]
It would be good to keep the old terms initially for compatibility, and maybe add a deprecation warning?

**Comment by craig-day** [comment]
closing this in favor of #216

**Pull request closed without merging**
