### PR TITLE
Move DisplayCopNames to RuboCop config file

### PR DESCRIPTION
**Pull request by bquorning**
cc @grosser

### CODE REVIEW

**Comment by grosser** [comment]
uuuh that is neat :D

**Comment by grosser** [comment]
👍

**Comment by bquorning** [comment]
What's up with Travis and Rubinius?

**Comment by grosser** [comment]
idk ... switch to plain rbx ?

**Comment by bquorning** [comment]
Let’s loop in @pschambacher who introduced rbx in the test suite.

**Comment by pschambacher** [comment]
You could try plain rbx or rbx-3? Otherwise just drop it, didn't manage to get enough rbx compat

**Comment by bquorning** [comment]
> just drop it

Done

**Pull request merged**
