### PR TITLE
Freeze string literals

### PR DESCRIPTION
**Pull request by pschambacher**
:octopus::computer:

/cc @grosser @bquorning 

### Description
Adding the magic string everywhere.

### Steps to merge
* [ ] :+1: from the team

### Risks
* None

### CODE REVIEW

**Comment by grosser** [comment]
👍

**Comment by bquorning** [comment]
Risks: none? Are you *sure* we don't mutate any string, anywhere?

**Comment by grosser** [comment]
tests would have blows up .. only code that reaches into shards to have
it's strings changed or changes strings that shards returns would be
affected

On Thu, May 12, 2016 at 8:57 PM, Benjamin Quorning <notifications@github.com

**Comment by bquorning** [comment]
:+1:

**Comment by pschambacher** [comment]
Pretty much what @grosser said. Now it's possible that some code isn't covered by the test suite (until Michael adds singlecov *wink wink*) but I also have a green build from other gems using this one so I'm confident.

**Pull request merged**
