### PR TITLE
Rails 5.2: create schema_migrations and internal_metadata on all shards

### PR DESCRIPTION
**Pull request by bogdan**
With the change in how `Migrator` is patched. We need to also patch the `initializer` to generate the metadata tables on all shards.

Reproduce from rails project:

``` sh
rake db:drop db:create db:migrate RAILS_ENV=test
```

### CODE REVIEW

**Comment by bogdan** [comment]
@bquorning can you take a look at this one? I believe this is 100% required to be compatible with 5.2.

**Comment by bquorning** [comment]
Thank you for the contribution @bogdan; I am sorry it has taken me a long (**long**) time to get around to this PR.

This one commit contains a lot of different things, and I think it would be beneficial to split it into a few commits, e.g.:

- One that adds a `#table_exists?` test helper method.
- One that adds an `.on_all_databases` method to `ConnectionSwitcher`.
…and a few others.

You remove some `alias_methods` calls in exchange for using `prepend`, but I think the resulting indentation changes make the PR unnecessarily hard to review. Could we keep that change for a follow-up PR?

**Comment by bogdan** [comment]
@bquorning I initially planned less things in this PR and tried to avoid all the changes at once. We can extract `table_exists?` and `on_all_databases` methods as a separated commit. However, this is not a big deal overall. I wasn't able to extract anything else. Change to use `prepend` instead of alias method was done for a reason I don't quite remember now.

I don't have time to perform all of multiple PRs with a lot of reviews things right now. Maybe I'll have it in a month or two... but who knows. But it will cause the work to be stretched across around 6 month.

This PR only takes 100 lines of code. I don't think it is a lot to review even though there are several things combined. 

Also, this code works in our production env since I opened this PR. This is the best guarantee I can make that everything is done right. However, it doesn't quite guarantee anything...

**Comment by lyfudesk** [comment]
> @bquorning can you take a look at this one? I believe this is 100% required to be compatible with 5.2.

Hi, which `active_record_shards` version do you use in `rails 5.2`?

**Comment by zhuravel** [comment]
@lyfudesk 
We’ve been using this branch in production with no issues since the release of Rails 5.2:
https://github.com/talkable/active_record_shards/tree/rails-5.2

It’s `master` from this repository with https://github.com/zendesk/active_record_shards/pull/184 and https://github.com/zendesk/active_record_shards/pull/191 merged.

**Comment by libo** [comment]
Hi @bogdan I just would like to point out that @bquorning didn't ask for "multiple PRs". It sounds to me he would just like separate atomic commits in this very PR. I think it's a good idea for future reference.

**Pull request closed without merging**
