### PR TITLE
Add a few warnings to the connection switcher and conf parser

### PR DESCRIPTION
**Pull request by bquorning**
Mostly extracted from #136.

### CODE REVIEW

**Comment by grosser** [comment]
... better double-check shards in kubernetes are integers first... I'll update here once I checked

**Comment by grosser** [comment]
kk, all good!

**Comment by codebender** [comment]
This was breaking change to the gem for everyone using springs to name the shards.  Why was this integer business important to anyone?

**Comment by grosser** [comment]
I think this was about sanitizing inputs ... I guess casting to int would have worked too.
Who was using strings as shards ? ... still need that ?

**Comment by codebender** [comment]
Hi @grosser, 

Having named shards is really handy when you want to read/write to a specific shard that is feature specific and not "account" ID specific like in the readme.

It looks like these other people also prefer string names: https://github.com/zendesk/active_record_shards/issues/195

**Comment by grosser** [comment]
yeah sounds reasonable, can you make a PR that semi-reverts this one and allows strings ?
(change the tests to test with a mix of strings and ints)
/cc @bquorning

**Comment by holmes2** [comment]
@bquorning @grosser 
Was there a reason why only integers are allowed for shard_names ?
I am trying to upgrade rails service to a higher version of this gem but still because of the shard name restriction we are not able to do it.
Is there a way to get around this shard naming restriction ?

**Comment by grosser** [comment]
I think this is because we only use it with integers and we wanted to warn our users from misconfiguration

**Pull request merged**
