### PR TITLE
Reorganize code

### PR DESCRIPTION
**Pull request by bquorning**
Create a file for patching each different version of `ActiveRecord`. With a growing number of ActiveRecord versions to support, I think we need to clean up our patches somehow.

What do you think, @osheroff, @grosser & @pschambacher?

### CODE REVIEW

**Comment by grosser** [comment]
not a big fan of that duplication :(

**Comment by bquorning** [comment]
Now with less duplication. Do you like the approach in general?

**Comment by grosser** [comment]
👍

**Comment by osheroff** [comment]
👍

**Pull request merged**
