### PR TITLE
Compatibility with Rails 4.2

### PR DESCRIPTION
**Pull request by pschambacher**
:bullettrain_side::arrow_upper_right: 

/cc @zendesk/zendesk-rails-upgraders 

### Description
Changed gemspec restriction
Add gemfile for travis
Setup ActiveSupport test order if possible

### Steps to merge
 - [x] :+1: of the team

### CODE REVIEW

**Comment by bquorning** [comment]
@osheroff, @pschambacher, any progress on this one?

**Comment by osheroff** [comment]
none from me; like I said, I'm ok disabling this functionality on later rails....

**Comment by bquorning** [comment]
@pschambacher is on holiday, so I took over this branch :-)

Marked that failing test as pending, did a `bundle update` and rebased.

Oh, and the build is green!

**Comment by osheroff** [comment]
:+1: then.

**Comment by bquorning** [comment]
```
Pushing gem to https://rubygems.org...
You do not have permission to push to this gem.
```
:cry:

**Pull request merged**
